/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repop2_juanmembreno;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class mairepo extends javax.swing.JFrame {

    /**
     * Creates new form mairepo
     */
    public mairepo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        hackeoreg = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        codigoR = new javax.swing.JTextField();
        riegoR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        modificarhackeoreg = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        codigoR1 = new javax.swing.JTextField();
        riegoR1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cb_regulares = new javax.swing.JComboBox<>();
        eliminarreg = new javax.swing.JDialog();
        cb_eliminar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        hackeosuper = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        codigoS = new javax.swing.JTextField();
        riegoS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        modificarsuperhackeo = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        codigoS1 = new javax.swing.JTextField();
        riegoS1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        cb_modificarsuper = new javax.swing.JComboBox<>();
        eliminarsuper = new javax.swing.JDialog();
        cb_eliminarsuper = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        simunlacionhackeo = new javax.swing.JDialog();
        cb_simulacion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        pg_1 = new javax.swing.JProgressBar();
        cargar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        caracteres = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Simulacion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        hackeoreg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Hackeo Regular");
        hackeoreg.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 95, -1, -1));
        hackeoreg.getContentPane().add(codigoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 194, 147, -1));
        hackeoreg.getContentPane().add(riegoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 194, 192, -1));

        jLabel2.setText("Nivel de riesgo");
        hackeoreg.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 160, -1, -1));

        jLabel3.setText("Codigo");
        hackeoreg.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 157, -1, -1));

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        hackeoreg.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 259, 223, 39));

        modificarhackeoreg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Modificar  Hackeo Regular");
        modificarhackeoreg.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 95, -1, -1));
        modificarhackeoreg.getContentPane().add(codigoR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 194, 147, -1));
        modificarhackeoreg.getContentPane().add(riegoR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 194, 192, -1));

        jLabel5.setText("Nivel de riesgo");
        modificarhackeoreg.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 160, -1, -1));

        jLabel6.setText("Codigo");
        modificarhackeoreg.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 157, -1, -1));

        jButton2.setText("Modificar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        modificarhackeoreg.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 259, 223, 39));

        cb_regulares.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_regularesItemStateChanged(evt);
            }
        });
        modificarhackeoreg.getContentPane().add(cb_regulares, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        cb_eliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_eliminarItemStateChanged(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nivel de riego", "Hackeos  Exitosos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla1);

        jButton3.setText("Eliminnar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarregLayout = new javax.swing.GroupLayout(eliminarreg.getContentPane());
        eliminarreg.getContentPane().setLayout(eliminarregLayout);
        eliminarregLayout.setHorizontalGroup(
            eliminarregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarregLayout.createSequentialGroup()
                .addGroup(eliminarregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarregLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eliminarregLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eliminarregLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        eliminarregLayout.setVerticalGroup(
            eliminarregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarregLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        hackeosuper.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Hackeo Super");
        hackeosuper.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 95, -1, -1));
        hackeosuper.getContentPane().add(codigoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 194, 147, -1));
        hackeosuper.getContentPane().add(riegoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 194, 192, -1));

        jLabel8.setText("Nivel de riesgo");
        hackeosuper.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 160, -1, -1));

        jLabel9.setText("Codigo");
        hackeosuper.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 157, -1, -1));

        jButton4.setText("Agregar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        hackeosuper.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 259, 223, 39));

        modificarsuperhackeo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Modificar  Hackeo Regular");
        modificarsuperhackeo.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 95, -1, -1));
        modificarsuperhackeo.getContentPane().add(codigoS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 194, 147, -1));
        modificarsuperhackeo.getContentPane().add(riegoS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 194, 192, -1));

        jLabel14.setText("Nivel de riesgo");
        modificarsuperhackeo.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 160, -1, -1));

        jLabel15.setText("Codigo");
        modificarsuperhackeo.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 157, -1, -1));

        jButton6.setText("Modificar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        modificarsuperhackeo.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 259, 223, 39));

        cb_modificarsuper.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_modificarsuperItemStateChanged(evt);
            }
        });
        modificarsuperhackeo.getContentPane().add(cb_modificarsuper, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        cb_eliminarsuper.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_eliminarsuperItemStateChanged(evt);
            }
        });

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nivel de riego", "Hackeos  Exitosos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla2);

        jButton5.setText("Eliminnar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarsuperLayout = new javax.swing.GroupLayout(eliminarsuper.getContentPane());
        eliminarsuper.getContentPane().setLayout(eliminarsuperLayout);
        eliminarsuperLayout.setHorizontalGroup(
            eliminarsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarsuperLayout.createSequentialGroup()
                .addGroup(eliminarsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarsuperLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(cb_eliminarsuper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eliminarsuperLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eliminarsuperLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarsuperLayout.setVerticalGroup(
            eliminarsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarsuperLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(cb_eliminarsuper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        simunlacionhackeo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_simulacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_simulacionItemStateChanged(evt);
            }
        });
        simunlacionhackeo.getContentPane().add(cb_simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 220, 30));

        jLabel10.setText("Simulacion");
        simunlacionhackeo.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));
        simunlacionhackeo.getContentPane().add(pg_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 400, 30));

        cargar.setText("jButton7");
        simunlacionhackeo.getContentPane().add(cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        guardar.setText("guardar");
        simunlacionhackeo.getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel11.setText("Cantidad  de   caracteres a probar");
        simunlacionhackeo.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        simunlacionhackeo.getContentPane().add(caracteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 170, -1));

        jButton7.setText("Hackear");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        simunlacionhackeo.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Admistrar");

        jMenu3.setText("Hackeo Regular");

        jMenuItem2.setText("Crear");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem4.setText("Modificar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem3.setText("Elimiar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenu4.setText("Super Hackeo");

        jMenuItem5.setText("Crear");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Modificar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("elimiar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Correr");

        Simulacion.setText("Simulacion");
        Simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimulacionActionPerformed(evt);
            }
        });
        jMenu2.add(Simulacion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
                administrahacksuper ap
                = new administrahacksuper("./hacksuper.cbm");
        ap.cargarArchivo();
        DefaultComboBoxModel modelo1
                = new DefaultComboBoxModel(
                        ap.getsuperhackeo().toArray());
        cb_eliminarsuper.setModel(modelo1);
        eliminarsuper();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        administrahackreg ap
                = new administrahackreg("./hackreg.cbm");
        ap.cargarArchivo();
        ap.gethackeoregular().add(new hackeoregular(0, Integer.parseInt(riegoR.getText()), codigoR.getText()));
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Hackeo  Agregado");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        administrahackreg ap
                = new administrahackreg("./hackreg.cbm");
        ap.cargarArchivo();
        DefaultComboBoxModel modelo1
                = new DefaultComboBoxModel(
                        ap.gethackeoregular().toArray());
        cb_regulares.setModel(modelo1);
        modificarhackeoreg();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void cb_regularesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_regularesItemStateChanged
        try {

            if (evt.getStateChange() == 1) {

                seleccionado1 = (hackeoregular) cb_regulares.getSelectedItem();
                codigoR1.setText(seleccionado1.getCodigo());
                riegoR1.setText(String.valueOf(seleccionado1.getNivelderiesgo()));
                //  seleccionadoexameneliminar = (examen) cb_exameneditar.getSelectedItem();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_regularesItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        administrahackreg ap
                = new administrahackreg("./hackreg.cbm");
        ap.cargarArchivo();
        for (int i = 0; i < ap.gethackeoregular().size(); i++) {
            if (seleccionado1.getCodigo().equals(ap.gethackeoregular().get(i).getCodigo())) {
                ap.gethackeoregular().remove(i);
            }
        }
        ap.gethackeoregular().add(new hackeoregular(0, Integer.parseInt(riegoR1.getText()), codigoR1.getText()));
        JOptionPane.showMessageDialog(this, "Modificado");
        ap.escribirArchivo();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        administrahacksuper ap
                = new administrahacksuper("./hacksuper.cbm");
        ap.cargarArchivo();
        ap.getsuperhackeo().add(new superhackeo(0, Integer.parseInt(riegoR.getText()), codigoR.getText()));
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "SuperHackeo  Agregado");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        administrahacksuper ap
                = new administrahacksuper("./hacksuper.cbm");
        ap.cargarArchivo();
        for (int i = 0; i < ap.getsuperhackeo().size(); i++) {
            if (ap.getsuperhackeo().get(i).getCodigo().equals(seleccionado2.getCodigo())) {
                ap.getsuperhackeo().remove(i);
            }
        }
        ap.getsuperhackeo().add(new superhackeo(0, Integer.parseInt(riegoS1.getText()), codigoS1.getText()));
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Modificado");
    }//GEN-LAST:event_jButton6MouseClicked

    private void cb_modificarsuperItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_modificarsuperItemStateChanged
        try {

            if (evt.getStateChange() == 1) {

                seleccionado2 = (superhackeo) cb_modificarsuper.getSelectedItem();
                codigoS1.setText(seleccionado1.getCodigo());
                riegoS1.setText(String.valueOf(seleccionado2.getNivelderiesgo()));
                //  seleccionadoexameneliminar = (examen) cb_exameneditar.getSelectedItem();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_modificarsuperItemStateChanged

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        administrahacksuper ap
                = new administrahacksuper("./hacksuper.cbm");
        ap.cargarArchivo();
        DefaultComboBoxModel modelo1
                = new DefaultComboBoxModel(
                        ap.getsuperhackeo().toArray());
        cb_modificarsuper.setModel(modelo1);
        modificarsuperhackeo();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        hackeoreg();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        hackeosuper();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        administrahackreg ap
                = new administrahackreg("./hackreg.cbm");
        ap.cargarArchivo();
        DefaultComboBoxModel modelo1
                = new DefaultComboBoxModel(
                        ap.gethackeoregular().toArray());
        cb_eliminar.setModel(modelo1);
        eliminarreg();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cb_eliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_eliminarItemStateChanged
        if (evt.getStateChange() == 2) {
            hackeoregular a = (hackeoregular) cb_eliminar.getSelectedItem();
            Object[] newrow = {a.getCodigo(), a.getNivelderiesgo(), a.getHackeosexitoso()};
            DefaultTableModel modelo
                    = (DefaultTableModel) tabla1.getModel();
            modelo.addRow(newrow);
            tabla1.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());               
        }
    }//GEN-LAST:event_cb_eliminarItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            administrahackreg ap
                    = new administrahackreg("./hackreg.cbm");
            ap.cargarArchivo();
            if (tabla1.getSelectedRow() >= 0) {
                DefaultTableModel modelo
                        = (DefaultTableModel) tabla1.getModel();
                for (int i = 0; i < ap.gethackeoregular().size(); i++) {
                    int row = tabla1.getSelectedRow();
                    // Component cuenta = tabla1.getc
                    String codigo = ((String) modelo.getValueAt(
                            tabla1.getSelectedRow(), 0));
                    String nombre = ((String) modelo.getValueAt(
                            tabla1.getSelectedRow(), 1));
                    //System.out.println(cuenta + "  ni" + nombre);
                    //  tabla1.setModel(modelo);
                    if (ap.gethackeoregular().get(i).getCodigo().equals(codigo)) {
                        //  System.out.println("si entra pero no hace nada");
                        ap.cargarArchivo();
                        ap.gethackeoregular().remove(i);
                        cb_regulares.removeItem(i);
                        ap.escribirArchivo();
                        DefaultComboBoxModel modelo1
                                = new DefaultComboBoxModel(
                                        ap.gethackeoregular().toArray());
                        cb_regulares.setModel(modelo1);
                    }
                }

                modelo.removeRow(tabla1.getSelectedRow());
                tabla1.setModel(modelo);

                ap.escribirArchivo();

                JOptionPane.showMessageDialog(this, " Regular Eliminado");
                //tf_edad_maxima.setText(maxima_edad());   
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void cb_eliminarsuperItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_eliminarsuperItemStateChanged
        if (evt.getStateChange() == 2) {
            hackeoregular a = (hackeoregular) cb_eliminarsuper.getSelectedItem();
            Object[] newrow = {a.getCodigo(), a.getNivelderiesgo(), a.getHackeosexitoso()};
            DefaultTableModel modelo
                    = (DefaultTableModel) tabla2.getModel();
            modelo.addRow(newrow);
            tabla2.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());               
        }
    }//GEN-LAST:event_cb_eliminarsuperItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
          try {
             administrahacksuper ap
                = new administrahacksuper("./hacksuper.cbm");
        ap.cargarArchivo();
            if (tabla2.getSelectedRow() >= 0) {
                DefaultTableModel modelo
                        = (DefaultTableModel) tabla2.getModel();
                for (int i = 0; i < ap.getsuperhackeo().size(); i++) {
                    int row = tabla2.getSelectedRow();
                    // Component cuenta = tabla1.getc
                    String codigo = ((String) modelo.getValueAt(
                            tabla2.getSelectedRow(), 0));
                    String nombre = ((String) modelo.getValueAt(
                            tabla2.getSelectedRow(), 1));
                    //System.out.println(cuenta + "  ni" + nombre);
                    //  tabla1.setModel(modelo);
                    if (ap.getsuperhackeo().get(i).getCodigo().equals(codigo)) {
                        //  System.out.println("si entra pero no hace nada");
                        ap.cargarArchivo();
                        ap.getsuperhackeo().remove(i);
                        cb_modificarsuper.removeItem(i);
                        ap.escribirArchivo();
                        DefaultComboBoxModel modelo1
                                = new DefaultComboBoxModel(
                                        ap.getsuperhackeo().toArray());
                        cb_modificarsuper.setModel(modelo1);
                    }
                }

                modelo.removeRow(tabla2.getSelectedRow());
                tabla2.setModel(modelo);

                ap.escribirArchivo();

                JOptionPane.showMessageDialog(this, "Super Eliminado");
                //tf_edad_maxima.setText(maxima_edad());   
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void SimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacionActionPerformed
         administrahacksuper ap
                = new administrahacksuper("./hacksuper.cbm");
        ap.cargarArchivo();
        administrahackreg ap2
                    = new administrahackreg("./hackreg.cbm");
            ap2.cargarArchivo();
             DefaultComboBoxModel modelo1
                = new DefaultComboBoxModel(
                        ap2.gethackeoregular().toArray());
        cb_simulacion.setModel(modelo1);
        
         modelo1
                = new DefaultComboBoxModel(
                        ap.getsuperhackeo().toArray());
        cb_simulacion.setModel(modelo1);
  
        simunlacionhackeo();
    }//GEN-LAST:event_SimulacionActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
   int r=(int)(Math.random()*10+1);
   if(bandera==1){
        ab=new hilo(pg_1,bandera,Integer.parseInt(caracteres.getText())*2,seleccionado3.getNivelderiesgo(),seleccionado4,seleccionado3);
        ab.start();
        /*guarda g=new guarda(this.pg_1,jl_hora);
        Thread proceso2 = new Thread(g);
        proceso2.start()*/
        
   }else{
       ab=new hilo(pg_1,bandera,Integer.parseInt(caracteres.getText())*2,seleccionado3.getNivelderiesgo(),seleccionado4,seleccionado3);
        ab.start();
   }
    }//GEN-LAST:event_jButton7MouseClicked

    private void cb_simulacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_simulacionItemStateChanged
        try {

            if (evt.getStateChange() == 1) {
                if(cb_simulacion.getSelectedItem() instanceof hackeoregular){
                    seleccionado3 = (hackeoregular) cb_simulacion.getSelectedItem();
                    bandera=1;
                }else if(cb_simulacion.getSelectedItem() instanceof superhackeo){
                seleccionado4= (superhackeo) cb_simulacion.getSelectedItem();
                //  seleccionadoexameneliminar = (examen) cb_exameneditar.getSelectedItem();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_simulacionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mairepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mairepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mairepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mairepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mairepo().setVisible(true);
            }
        });
    }

    private void hackeoreg() {
        hackeoreg.setModal(true);
        hackeoreg.pack();
        hackeoreg.setLocationRelativeTo(this);
        hackeoreg.setVisible(true);
    }

    private void modificarhackeoreg() {
        modificarhackeoreg.setModal(true);
        modificarhackeoreg.pack();
        modificarhackeoreg.setLocationRelativeTo(this);
        modificarhackeoreg.setVisible(true);
    }

    private void eliminarreg() {
        eliminarreg.setModal(true);
        eliminarreg.pack();
        eliminarreg.setLocationRelativeTo(this);
        eliminarreg.setVisible(true);
    }

    private void hackeosuper() {
        hackeosuper.setModal(true);
        hackeosuper.pack();
        hackeosuper.setLocationRelativeTo(this);
        hackeosuper.setVisible(true);
    }

    private void modificarsuperhackeo() {
        modificarsuperhackeo.setModal(true);
        modificarsuperhackeo.pack();
        modificarsuperhackeo.setLocationRelativeTo(this);
        modificarsuperhackeo.setVisible(true);
    }
     private void eliminarsuper() {
        eliminarsuper.setModal(true);
        eliminarsuper.pack();
        eliminarsuper.setLocationRelativeTo(this);
        eliminarsuper.setVisible(true);
    }
      private void simunlacionhackeo() {
        simunlacionhackeo.setModal(true);
        simunlacionhackeo.pack();
        simunlacionhackeo.setLocationRelativeTo(this);
        simunlacionhackeo.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Simulacion;
    private javax.swing.JTextField caracteres;
    private javax.swing.JButton cargar;
    private javax.swing.JComboBox<String> cb_eliminar;
    private javax.swing.JComboBox<String> cb_eliminarsuper;
    private javax.swing.JComboBox<String> cb_modificarsuper;
    private javax.swing.JComboBox<String> cb_regulares;
    private javax.swing.JComboBox<String> cb_simulacion;
    private javax.swing.JTextField codigoR;
    private javax.swing.JTextField codigoR1;
    private javax.swing.JTextField codigoS;
    private javax.swing.JTextField codigoS1;
    private javax.swing.JDialog eliminarreg;
    private javax.swing.JDialog eliminarsuper;
    private javax.swing.JButton guardar;
    private javax.swing.JDialog hackeoreg;
    private javax.swing.JDialog hackeosuper;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog modificarhackeoreg;
    private javax.swing.JDialog modificarsuperhackeo;
    private javax.swing.JProgressBar pg_1;
    private javax.swing.JTextField riegoR;
    private javax.swing.JTextField riegoR1;
    private javax.swing.JTextField riegoS;
    private javax.swing.JTextField riegoS1;
    private javax.swing.JDialog simunlacionhackeo;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
  hackeoregular seleccionado1;
    superhackeo seleccionado2;
    hackeoregular seleccionado3;
    superhackeo seleccionado4;
    int   bandera;
    hilo   ab;
}
